### PR TITLE
qwertz layout added

### PR DESCRIPTION
**Pull request by aisbergde**
related to #22 
qwerty has been copied as qwertz, 
copy modified and added to layout selection

### CODE REVIEW

**Comment by peterekepeter** [comment]
Code looks good! Needs to be tested, then merge!

**Comment by Dakkaron** [comment]
Is there are reaon this hasn't been merged? I want this as well.

**Comment by peterekepeter** [comment]
Well I don't have write access, @gazlaws-dev is not very active lately. It took me months to get a PR in as well. I've been considering forking and merging stuff and making a separate release but couldn't find the time for it.

**Comment by Dakkaron** [comment]
Ok, makes sense. I thought, maybe you had maintainer privileges or something.

Thanks for the work and the reply!

**Comment by gazlaws-dev** [comment]
Hi @peterekepeter , I've invited you to be a collaborator for this repo! I'd love to keep this project alive, even when I'm away for a while :)

**Comment by peterekepeter** [comment]
Thank you for the invite! I might not always have the time, but I'll take a look once in a while to see sort the issues and see if things are merge-able. Though for big changes it would be nice ti still have your input @gazlaws-dev

**Pull request merged**
