### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by peterekepeter**
Better later than never! No worries, life is 1st priority.

Since I've created the original pull request, I have also added some additional improvements
 - github actions integration for CI
 - separate keyboard size for portrait, landscape
 - dvorak layout (though improvmenets might be needed by, maybe by someone who actually uses dvorak)
 - refactored the way settings are used, cetralised them into a single file instead of having the application randomly reading it and writing it from various places
 - cleaned up repo by removing files which are made obsolete by programatically generating the layout

I've made some cherry picks onto your master, fixed merged conflicts and tested on my phone, so this should be conflict free. Though I'm a bit confused on what gradle is doing, I needed up update Android Studio before I was able to test after merging with your master.

### CODE REVIEW

**Comment by peterekepeter** [comment]
I've added updates to the project files. This fixes the CI run, you should be able to see it here https://github.com/peterekepeter/codeboard/actions/runs/78851229

**Comment by peterekepeter** [comment]
also, might want to update the project board, I think https://github.com/gazlaws-dev/codeboard/issues/49 can be closed

**Comment by gazlaws-dev** [comment]
Hi Peter, I've made changes to master, before I noticed your PR. I'll make sure to work on a branch next time, so we don't have merge conflicts in the future. Also we can assign issues we're working on.

This is the first open source project I'm managing so apologies for the noob question: Do you have a resource I can look at to understand CI?

The aim is to have totally customizable keyboards, that the user can save as "Profiles".  Centralizing the prefs is a great idea! For now, if you resolve the conflicts, I can merge it in.

**Comment by peterekepeter** [comment]
These were changes I did between my previous pull request and well, today I guess. I should have added them to the previous pull request so that they all get merged in one go. This way I had to do some merge conflicts, well twice, but this second time was a bit easier.

I also noticed some merge conflict bugs, the sound toggle was toggling theme by accident.

I've fixed the bug, made a few cleanups, should be good now.

CI is basically some computer running the build command and test command for every commit. This is useful since you get build and test status report right in your pull requests. This is useful because sometimes people forget to run the tests and also during pull requests both the author and reviewer know if build and test passes without needing to manually pull and run and everything. It also makes sure that the project is healthy, can be compiled without errors.

It's much more simple than documentation makes it sound, it's just a computer running the build&test commands, but please do check out https://github.com/features/actions

**Comment by peterekepeter** [comment]
On top of that, you even get a cool status badge, perfect for the repository readme
Codeboard Android CI

**Pull request merged**
