### PR TITLE
Set switchedKeyboard before showing keyboard picker.

### LINKED ISSUE #51: Unexpected space when switching keyboards
When I long press the space button to switch the keyboard, a space is incorrectly written to the current text box at same time the popup is opened.

### PR DESCRIPTION
**Pull request by DDoSolitary**
Fix #51.

### CODE REVIEW

**Comment by gazlaws-dev** [comment]
This only changes the variable, not the order of onKey and onKeyLongPress. Also, I cannot recreate issue #54

**Comment by DDoSolitary** [comment]
I'm quite surprised because I've observed this in a number of ROMs, including resurrection remix pie and MIUI(Xiaomi’s official ROM) pie. I can upload a screen record of this issue if you want.

I'm not an Android developer but from what I can see from the code, I guess the following happens when I long press the space button.

1. I press down the space button, `onPress` is called and a timer is started.
2. Timer goes up and `onKeyLongPress` is called.
3. The keyboard picker is shown and the space button is released (although I didn't release my finger, but the button does get released. It's easier to notice if you experiment with Gboard, because background color of the button changes after the picker pops up)
4. `onKey` is called but `switchedKeyboard` hasn't been set yet, so a space is written.
5. `showInputMethodPicker` returns and `switchedKeyboard` gets set.

I don't know if `showInputMethodPicker` returns after the picker is shown or after it is closed. But given that you can't reproduce this issue, I think it's reasonable to assume the former. If that is the case, then I guess there's some sort of racing happening here: on your device `showInputMethodPicker` returns faster and the flag is set before `onKey` reads it, while on my device `onKey` runs faster.

Again, I'm not an Android developer, so I might have some mistakes in my theory and I can't test my patch because I don't know how to build an debug this app

**Comment by DDoSolitary** [comment]
[screenrecord.tar.gz](https://github.com/gazlaws-dev/codeboard/files/2953148/screenrecord.tar.gz)

**Comment by gazlaws-dev** [comment]
Thanks for looking into it! I'll upload an apk here, please do test it and let me know

**Comment by DDoSolitary** [comment]
Just tested and it works fine, but I just found out it might not be my patch doing the magic:

1. There's already a commit in the commit history to address this issue. I checked the version I was having problem with (installed from Play Store) and found that its rather old. It seems that the version on Play Store is even older than your commit to fix this.
2. I re-read the code and noticed that `onKeyLongPress` is executed in the UI thread rather than a separate thread as I previously thought, so there's no chance for a race to occur (or it's an Android's bug...)

So could you please upload an apk with my commit reverted to verify this? And it will be nice to have an up-to-date version available at Play Store after this issue (and probably other issues that you want to fix now) is properly dealt with.

**Comment by gazlaws-dev** [comment]
Yeah, I really need to update the Play Store version. Here's the original apk
[app_og.zip](https://github.com/gazlaws-dev/codeboard/files/2953571/app_og.zip)

**Comment by DDoSolitary** [comment]
The original one works fine either, so my patch is completely unnecessary 🤣

**Pull request merged**
