### PR TITLE
Added button borders

### PR DESCRIPTION
**Pull request by PawelPleskaczynski**
I like this keyboard but typing on it was kinda hard without borders, so I added them in this PR

image

### CODE REVIEW

**Comment by gazlaws-dev** [comment]
Apologies for not checking earlier, I'll review the code and merge in a few days. Screenshot looks good!

**Comment by PawelPleskaczynski** [comment]
No problem! I have been using the keyboard with modifications occasionally and I have to say that it's really far more convenient to type with key borders

**Comment by gazlaws-dev** [comment]
The latest merges makes the keyboard more flexible, but now you'll have to resolve the conflicts.

**Comment by PawelPleskaczynski** [comment]
@gazlaws-dev okay, I rebased, you can try to merge now

**Pull request closed without merging**
